<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>

<link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/humanity/jquery-ui.css" rel="stylesheet" type="text/css"/>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script>
<?php
if($this->dojo()->isEnabled())
{
    $this->dojo()
             ->addStylesheetModule('dijit.themes.nihilo');
    echo $this->dojo();
}
?>
</script>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"><title>P&eacute;tala Azul - DataGrid Examples</title>
<link type="text/css" rel="stylesheet" href="<?php echo $this->url; ?>public/styles/styles.css">
<?php echo $this->headScript();?>
</head>
<body class="nihilo">

<table style="width:900px;" align="center" cellpadding="0" cellspacing="0">
<tr <?php if($this->action =='cs'){echo "style='display:none;'";}?>>
<td style="background-color:#F5F5F5; border:0px;">
<div style="background-image:url(<?php echo $this->url; ?>public/images/grid.jpg); height:250px;width:900px; background-repeat:none;">
<div style="height:37px;"><a href="/"><img border="0" width="220" height="30" src="<?php echo $this->url; ?>public/images/blank.gif"></img></a></div>
<ul>
    <li>.:<a href="<?php echo $this->baseUrl('default/site/basic')?>">Basic Example with auto-complete</a><span>What happens when you just pass the Zend_Db_Select instance</span></li>
    <li>.:<a href="<?php echo $this->baseUrl('default/site/mass')?>">Mass Actions</a><span>Use mass actions to perform the same action on multiple records.</span></li>
    <li>.:<a href="<?php echo $this->baseUrl('default/site/extra')?>">Extra Columns</a><span>Add extra fields with content from records to your grid</span></li>
    <li>.:<a href="<?php echo $this->baseUrl('default/site/columns')?>">Extra Rows</a><span>Insert extra columns in a variety of positions in your grid</span></li>
    <li>.:<a href="<?php echo $this->baseUrl('default/site/filters')?>">Advanced Filters</a><span>Create custom filters and take advantage of the auto filters</span></li>
    <li>.:<a href="<?php echo $this->baseUrl('default/site/conditional')?>">Conditional Rendering</a><span>Apply rules to format cells content</span></li>
    <li>.:<a href="<?php echo $this->baseUrl('default/site/ajax')?>">Ajax</a><span>Use ajax to interact with the grid</span></li>
</ul>
<ul>
    <li>.:<a href="<?php echo $this->baseUrl('default/site/crud')?>">CRUD Operations with Bulk Actions</a><span>With auto-validation <a href="<?php echo $this->baseUrl('default/site/form')?>">Bulk Actions Vertical</a>,<a href="<?php echo $this->baseUrl('default/site/form1')?>">Bulk Actions Horizontal</a> </span></li>
    <li>.:Data Sources<span>Displays data from db (Zend_Db && Doctrine), <a href="<?php echo $this->baseUrl('default/site/csv')?>">CSV</a>, <a href="<?php echo $this->baseUrl('default/site/feed')?>">XML</a>, <a href="<?php echo $this->baseUrl('default/site/array')?>">Array</a></span></li>
    <li>.:Render in different formats<span>Deploy your data as a table, <a href="<?php echo $this->baseUrl('default/jqgrid')?>">jqGrid</a>, <a href="<?php echo $this->baseUrl('default/site/ofc')?>">Open Flash Chart</a></span></li>
    <li>.:<a href="<?php echo $this->baseUrl('default/site/template')?>">Templating</a><span>Use different templates for each grid</span></li>
    <li>.:<a href="<?php echo $this->baseUrl('default/site/hrow')?>">Horizontal Row</a><span>Split a set of records with an horizontal row</span></li>
    <li>.:<a href="<?php echo $this->baseUrl('default/site/detail')?>">Detail View</a><span>See records details</span></li>
    <li>.:<a href="<?php echo $this->baseUrl('default/site/multi')?>">Multiple Grids per page</a><span>Use several grids per page without interference between them</span></li>
</ul>
</div>

</td>
</tr>

<tr>
<td style="background-color:#F2F2F2; border:0px;">
<?php if($this->action =='basic'){?>
    <span style="font-size:10px; border:1px solid #AAA; display:block; margin-bottom:10px; padding:5px; background-color:#DEDEDE;"><strong>NEW</strong>: Try the auto-complete filtering.</span>
    <?php }?>
<?php if($this->action=='ofc'){?>

    <div style="border:1px solid #111; padding:5px;margin:5px; font-size:12px; background-color:#DEDEDE;">Bar Types:
    <?php foreach ($this->graphs as $value):?>

    <a style="font-size:10px;text-decoration:none; margin:4px;color:maroon;" href="<?php echo $this->url ?>default/site/ofc/type/<?php echo $value?>"><?php echo ucwords(str_replace('_',' ',$value))?></a>

    <?php endforeach;?>
    </div>

<?php }else{?>
<span style="font-size:10px; border:1px solid #dedede; display:block; margin-bottom:10px; padding:5px; background-color:beige;">Refine your search using common tricks:
    &lt;value | =value | &gt;value | &lt;=value | &gt;=value | *value | value* | *value* | <>value | value1,value2,... | number<>number
</span>
<?php }?>

<?php if($this->action =='filters'){?>
<span style="font-size:10px; border:1px solid #dedede; display:block; margin-bottom:10px; padding:5px; background-color:#DEDEDE;">
Only show countries with at least: <?php
$continents = array('Europe');
$array = array(''=>'--choose--',10000000=>'10 Millions',100000000=>'100 Millions',500000000=>'500 Millions',1000000000=>'1 Billion');
echo $this->formSelect('new_filter',$this->pages->getParam('new_filter'),array('onChange'=>'_gridChangeFilters()'),$array);?> people from <?php echo $this->formCheckbox('filter_country',$this->pages->getParam('filter_country'),array('onChange'=>'_gridChangeFilters()'),$continents);?> Europe
</span>
<?php }?>
<div id="grid">
<?php  echo $this->pages; ?>
<?php /* ?>
<?php echo $this->pages->render('detail'); ?>
<?php echo $this->pages->render('addButton'); ?>
<?php echo $this->pages->render('message'); ?>
<?php echo $this->pages->render('form'); ?>
<?php echo $this->pages->render('start'); ?>
<?php echo $this->pages->render('extra'); ?>
<?php echo $this->pages->render('header'); ?>
<?php echo $this->pages->render('titles'); ?>
<?php echo $this->pages->render('filters'); ?>
<?php echo $this->pages->render('grid'); ?>
<?php echo $this->pages->render('pagination'); ?>
<?php echo $this->pages->render('end'); ?>
<?php */?>
</div>

<br>
<div id="grid">
<?php echo $this->pages2; ?>
</div>
</td>
</tr>
</table>
<?php if(stripos($_SERVER['HTTP_HOST'],'zfdatagrid')!==false):?>
<!-- Piwik -->
<script type="text/javascript">
var pkBaseURL = (("https:" == document.location.protocol) ? "https://petala-azul.com/piwik/" : "http://petala-azul.com/piwik/");
document.write(unescape("%3Cscript src='" + pkBaseURL + "piwik.js' type='text/javascript'%3E%3C/script%3E"));
</script><script type="text/javascript">
try {
var piwikTracker = Piwik.getTracker(pkBaseURL + "piwik.php", 1);
piwikTracker.trackPageView();
piwikTracker.enableLinkTracking();
} catch( err ) {}
</script><noscript><p><img src="http://petala-azul.com/piwik/piwik.php?idsite=1" style="border:0" alt=""/></p></noscript>

<!-- End Piwik Tag -->
<?php endif;?>
</body></html>