<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"><title>P&eacute;tala Azul - DataGrid Examples</title>
<link type="text/css" rel="stylesheet" href="<?php echo $this->url; ?>public/styles/estilos.css">
<?php echo $this->headScript();?>
<style type="text/css">
li {
padding:0px;margin:0px;
width:330px;
line-height:100%;
left:30px;
}

#menu a,#menu a:hover{
	color:#333;
text-decoration:none;
}
</style>
</head>
<body>
<table style="width:900px;" align="center" cellpadding="0" cellspacing="0">
<tr>
<td style="background-color:#F2F2F2; border:0px;">
<div style="position:relative; background-image:url(<?php echo $this->url; ?>public/images/grid.jpg); height:100px;width:900px;">
<div style="float:left;top:20px;position:relative;left:20px;"><a href="<?php echo $this->url; ?>"><img border="0" width="230" height="50" src="<?php echo $this->url; ?>public/images/blank.gif"></img></a></div>
<div id="menu" style="border:0;position:relative; top:20px;margin-left:300px;margin-right:200px;font-size:12px;">
<strong style="color:maroon;">Choose another example:</strong>
<select onchange="window.location=this.value" style=" padding:2px;font-size:12px;">
       <option value="<?php echo $this->url ?>default/site/basic" <?php if($this->action=='basic'){echo " selected ";}?>>Basic example - $db->select()->from('table');</option>
       <option value="<?php echo $this->url ?>default/site/ofc" <?php if($this->action=='ofc'){echo " selected ";}?>>Open FLash Chart - Simple Implementation</option>
       <option value="<?php echo $this->url ?>default/jqgrid" >Jqgrid - From http://www.trirand.com/blog/ </option>
       <option value="<?php echo $this->url ?>default/site/ajax" <?php if($this->action=='ajax'){echo " selected ";}?>>Basic example with AJAX;</option>
        <option value="<?php echo $this->url ?>default/site/extra" <?php if($this->action=='extra'){echo " selected ";}?>>Extra Fields - Extra Fields with custom content</option>
        <option value="<?php echo $this->url ?>default/site/filters" <?php if($this->action=='filters'){echo " selected ";}?>>Advanced Filters - Auto Filters</option>
        <option value="<?php echo $this->url ?>default/site/crud" <?php if($this->action=='crud'){echo " selected ";}?>>CRUD operations - Create, Read, Update and delete operations</option>
        <option value="<?php echo $this->url ?>default/site/column" <?php if($this->action=='column'){echo " selected ";}?>>Columns - Build Using Bvb_Grid_Column</option>
        <option value="<?php echo $this->url ?>default/site/hrow" <?php if($this->action=='hrow'){echo " selected ";}?>>Horizontal Row - Split the grid by sections</option>
        <option value="<?php echo $this->url ?>default/site/template" <?php if($this->action=='template'){echo " selected ";}?>>Custom Template - Outside the Grid Path</option>
        <option value="<?php echo $this->url ?>default/site/feed" <?php if($this->action=='feed'){echo " selected ";}?>>Feed - Using RSS as datasource</option>
        <option value="<?php echo $this->url ?>default/site/csv" <?php if($this->action=='csv'){echo " selected ";}?>>CSV - Using CSV file as datasource</option>
</select>
<a target="_blank" href="<?php echo $this->url ?>default/site/code">Source code for this controller</a> |
<a href="http://www.zfdatagrid.com/">Back to blog</a>
</div>
</div>

</td>
</tr>

<tr>
<td style="background-color:#F2F2F2; border:0px;">

<?php if($this->action=='ofc'){?>

    <div style="border:1px solid #111; padding:5px;margin:5px; font-size:12px; background-color:#DEDEDE;">Bar Types:
    <?php foreach ($this->graphs as $value):?>

    <a style="font-size:10px;text-decoration:none; margin:4px;color:maroon;" href="<?php echo $this->url ?>default/site/ofc/type/<?php echo $value?>"><?php echo ucwords(str_replace('_',' ',$value))?></a>

    <?php endforeach;?>
    </div>

<?php }?>
<div id="grid">
<?php echo $this->pages; ?>
</div>
<div id="grid">
<?php echo $this->pages1; ?>
</div>

</td>
</tr>
</table>
<?php if(stripos($_SERVER['HTTP_HOST'],'zfdatagrid')!==false):?>
<!-- Piwik -->
<script type="text/javascript">
var pkBaseURL = (("https:" == document.location.protocol) ? "https://petala-azul.com/piwik/" : "http://petala-azul.com/piwik/");
document.write(unescape("%3Cscript src='" + pkBaseURL + "piwik.js' type='text/javascript'%3E%3C/script%3E"));
</script><script type="text/javascript">
try {
var piwikTracker = Piwik.getTracker(pkBaseURL + "piwik.php", 1);
piwikTracker.trackPageView();
piwikTracker.enableLinkTracking();
} catch( err ) {}
</script><noscript><p><img src="http://petala-azul.com/piwik/piwik.php?idsite=1" style="border:0" alt=""/></p></noscript>

<!-- End Piwik Tag -->
<?php endif;?>
</body></html>


