<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"><title>P&eacute;tala Azul - DataGrid Examples</title>
<link type="text/css" rel="stylesheet" href="<?php echo $this->url; ?>public/styles/styles.css">
<?php echo $this->headScript();?>
<style type="text/css">
ul {
	padding:0;
	margin:0;
	margin-left:15px;
	list-style:none;
	width:430px;
	float:left;
}

li{
    color:#E88A16;
	font-size:11px;
	font-weight:bold;
}

li span{
    color:#000;
	display:block;
	padding-left:20px;
	font-weight:normal;
}

li a, li a:VISITED {
	color:#E88A16;
	letter-spacing:1px;
	text-decoration:none;
}
</style>
</head>
<body>
<table style="width:900px;" align="center" cellpadding="0" cellspacing="0">
<tr>
<td style="background-color:#F5F5F5; border:0px;">
<div style="background-image:url(<?php echo $this->url; ?>public/images/grid.jpg); height:250px;width:900px;">
<div style="height:37px;"><a href="/"><img border="0" width="220" height="30" src="<?php echo $this->url; ?>public/images/blank.gif"></img></a></div>
<ul>
    <li>.:<a href="<?php echo $this->baseUrl('default/site/basic')?>">Basic Example</a><span>What happens when you just pass the Zend_Db_Select instance</span></li>
    <li>.:<a href="<?php echo $this->baseUrl('default/site/mass')?>">Mass Actions</a><span>Use mass actions to perform the same action on multiple records.</span></li>
    <li>.:<a href="<?php echo $this->baseUrl('default/site/extra')?>">Extra Columns</a><span>Add extra fields with content from records to your grid</span></li>
    <li>.:<a href="<?php echo $this->baseUrl('default/site/columns')?>">Extra Rows</a><span>Insert extra columns in a variety of positions in your grid</span></li>
    <li>.:<a href="<?php echo $this->baseUrl('default/site/filters')?>">Advanced Filters</a><span>Create custom filters and take advantage of the auto filters</span></li>
    <li>.:<a href="<?php echo $this->baseUrl('default/site/conditional')?>">Conditional Rendering</a><span>Apply rules to format cells content</span></li>
    <li>.:<a href="<?php echo $this->baseUrl('default/site/ajax')?>">Ajax</a><span>Use ajax to interact with the grid</span></li>
</ul>
<ul>
    <li>.:<a href="<?php echo $this->baseUrl('default/site/crud')?>">CRUD Operations</a><span>Perform CRUD operations with auto-validation </span></li>
    <li>.:Data Sources<span>Display data from db, <a href="<?php echo $this->baseUrl('default/site/excel')?>">Excel Files</a>, <a href="<?php echo $this->baseUrl('default/site/csv')?>">CSV</a>, <a href="<?php echo $this->baseUrl('default/site/feed')?>">XML</a>, <a href="<?php echo $this->baseUrl('default/site/array')?>">Array</a>, Build your own.</span></li>
    <li>.:Render in different formats<span>Deploy your data as a table, <a href="<?php echo $this->baseUrl('default/jqgrid')?>">jqGrid</a>, <a href="<?php echo $this->baseUrl('default/site/ofc')?>">Open Flash Chart</a></span></li>
    <li>.:<a href="<?php echo $this->baseUrl('default/site/template')?>">Templating</a><span>Use different templates for each grid</span></li>
    <li>.:<a href="<?php echo $this->baseUrl('default/site/hrow')?>">Horizontal Row</a><span>Split a set of records with an horizontal row</span></li>
    <li>.:<a href="<?php echo $this->baseUrl('default/site/detail')?>">Detail View</a><span>See records details</span></li>
    <li>.:<a href="<?php echo $this->baseUrl('default/site/multi')?>">Multiple Grids per page</a><span>Use several grids per page without interference between them</span></li>
</ul>
</div>

</td>
</tr>

<tr>
<td style="background-color:#F2F2F2; border:0px;">

<?php if($this->action=='ofc'){?>

    <div style="border:1px solid #111; padding:5px;margin:5px; font-size:12px; background-color:#DEDEDE;">Bar Types:
    <?php foreach ($this->graphs as $value):?>

    <a style="font-size:10px;text-decoration:none; margin:4px;color:maroon;" href="<?php echo $this->url ?>default/site/ofc/type/<?php echo $value?>"><?php echo ucwords(str_replace('_',' ',$value))?></a>

    <?php endforeach;?>
    </div>

<?php }else{?>
<span style="font-size:10px; border:1px solid #dedede; display:block; margin-bottom:10px; padding:5px; background-color:beige;">You can refine your search by using commom tricks:
    &lt;value | &gt;value | &lt;=value | &gt;=value | *value | value* | *value* | <>value | value1,value2,value3 | number<>number
</span>
<?php }?>
<div id="grid">
<?php  echo $this->pages; ?>
<?php /* ?>
<?php echo $this->pages->render('detail'); ?>
<?php echo $this->pages->render('message'); ?>
<?php echo $this->pages->render('addButton'); ?>
<?php echo $this->pages->render('form'); ?>
<?php echo $this->pages->render('start'); ?>
<?php echo $this->pages->render('extra'); ?>
<?php echo $this->pages->render('header'); ?>
<?php echo $this->pages->render('titles'); ?>
<?php echo $this->pages->render('filters'); ?>
<?php echo $this->pages->render('grid'); ?>
<?php echo $this->pages->render('pagination'); ?>
<?php echo $this->pages->render('end'); ?>
<?php */?>
</div>

<br></br>
<div id="grid">
<?php echo $this->pages2; ?>
</div>
<br></br>
</td>
</tr>
</table>
<?php if(stripos($_SERVER['HTTP_HOST'],'zfdatagrid')!==false):?>
<!-- Piwik -->
<script type="text/javascript">
var pkBaseURL = (("https:" == document.location.protocol) ? "https://petala-azul.com/piwik/" : "http://petala-azul.com/piwik/");
document.write(unescape("%3Cscript src='" + pkBaseURL + "piwik.js' type='text/javascript'%3E%3C/script%3E"));
</script><script type="text/javascript">
try {
var piwikTracker = Piwik.getTracker(pkBaseURL + "piwik.php", 1);
piwikTracker.trackPageView();
piwikTracker.enableLinkTracking();
} catch( err ) {}
</script><noscript><p><img src="http://petala-azul.com/piwik/piwik.php?idsite=1" style="border:0" alt=""/></p></noscript>

<!-- End Piwik Tag -->
<?php endif;?>
</body></html>