CREATE TABLE City (
	ID INT NOT NULL AUTO_INCREMENT,
	Name CHAR(35) DEFAULT '' NOT NULL,
	CountryCode CHAR(3) DEFAULT '' NOT NULL,
	District CHAR(20) DEFAULT '' NOT NULL,
	Population INT DEFAULT 0 NOT NULL,
	PRIMARY KEY (ID)
) ENGINE=MyISAM;

