<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<title>Source Code :: ZFDatagrid jqGrid Examples</title>

<style type="text/css">
.num {
float: left;
color: gray;
text-align: right;
margin-right: 6pt;
padding-right: 6pt;
border-right: 1px solid gray;}
</style>
</head>
<body>
<?php
function highlight_num($file)
{
 echo '<code class="num">', implode(range(1, count(file($file))), '<br />'), '</code>';
 highlight_file($file);
}

highlight_num(getcwd().'/application/controllers/JqgridController.php');
?>
</body></html>